[VIVO-1865] - Add etag generation config
awoods/vivo-solr pull request #3
Opened 2020-05-18 23:56 UTC by gneissone

See https://jira.lyrasis.org/browse/VIVO-1865

The solrconfig.xml included does not include processing logic for etags. See etag processing chain from old file here: https://github.com/vivo-project/Vitro/blob/vitro-1.10.0/home/src/main/resources/solr/conf/solrconfig.xml#L1832

Without this fix, the caching scheme described at https://wiki.lyrasis.org/display/VIVODOC111x/Use+HTTP+caching+to+improve+performance does not work.

This pull request copies over the processing chain from the old config. After inclusion, etags are generated again when the search index updates.

2020-05-18 23:59 UTC, awoods commented
How do you recommend I test this, @gneissone ?

2020-05-19 00:06 UTC, gneissone commented
Make sure http.createCacheHeaders = true in runtime.properties
Inspect a profile page in VIVO v1.11.x and look at the response headers. 
If the ETag field is present, it will be missing a unique hash
Modify solrconfig.xml to include changes 
Restart Solr
Re-inspect profile page headers
ETag should be present with unique hash

See screenshot
<img width="1292" alt="Screen Shot 2020-05-18 at 6 03 00 PM" src="https://user-images.githubusercontent.com/10748475/82270529-58799900-9932-11ea-952d-d7f3a5e02871.png">

@hudajkhan

2020-05-19 02:56 UTC, awoods commented
Thanks for the details, @gneissone .
Unfortunately, I have not been able to reproduce a difference between cache headers with and without this update.
Let's sort it out tomorrow.

2020-05-19 02:56 UTC, awoods commented
p.s. Why the whitespace updates!?

2020-05-19 03:29 UTC, gneissone commented
Because no whitespace is the best whitespace, I guess

2020-05-19 03:30 UTC, gneissone commented
You are still getting etags with unique hashes with the solrconfig.xml included in this repo?

2020-05-19 03:39 UTC, awoods commented
My situation may be a result of the data in my local installation (https://github.com/vivo-project/sample-data/blob/master/sample-data.n3).
When I go to an individual, the "display" URLs all produce 404s, e.g. http://localhost:8080/vivo/display/n128
However, the "individual" URLs returns successfully, e.g. http://localhost:8080/vivo/individual?uri=http%3A%2F%2Flocalhost%3A8080%2Fvivo%2Findividual%2Fn128

I get no `etag` header on the "individual" requests, before and after the solr config update. When I go directly to solr, I always get `etags`... before and after the solr config update.

That is where I am.

2020-05-19 03:59 UTC, gneissone commented
Right, for the display shortcut to work I think the default namespace in runtime.properties has to match the namespace of the data. I am not seeing etags for the individual?uri= method either. Looks like the intention was to include those (based on https://github.com/vivo-project/Vitro/blob/master/api/src/main/java/edu/cornell/mannlib/vitro/webapp/filters/CachingResponseFilter.java#L211) but the actual logic doesn't cover that case (https://github.com/vivo-project/Vitro/blob/master/api/src/main/java/edu/cornell/mannlib/vitro/webapp/filters/CachingResponseFilter.java#L239).

2020-05-19 17:06 UTC, awoods commented
By updating my runtime.properties with the following, I am able to verify the change in this functionality:
```
Vitro.defaultNamespace = http://localhost:8080/vivo/individual/
```

2020-05-19 17:13 UTC, awoods requested changes
Verified functionality.
Would you mind removing the unrelated whitespace changes from this pull-request?

2020-05-19 18:42 UTC, gneissone commented
@awoods Okay, thanks. Pulled back the whitespace changes.

2020-05-19 19:29 UTC, awoods approved these changes

2020-05-22 17:04 UTC, roflinn approved these changes
Approved

2020-05-22 17:05 UTC, merged